export const visits = {"page":{"current_page":1,"next_page":2,"prev_page":null,"total_pages":2,"page_size":40,"count":3},"links":{"next":"http://api.upsell.adjoint.in/portal/api/stores/list/?org_node=1&page=2&page_size=40&status=True","previous":null},"results":[{"outlet_id":"337835","visit_id":"VEC823823794723495","outlet_type":"Pan Shop","wd_id":"BL5038","market_name":"Bangalore","merchandiser_name":"Arun","branch":"Bangalore","ra_type":"RA 1","ra_color":"Amber Yellow","beat_name":"Monday","name":"Nandana Pan","contact_no":"7417710744","store_status":true,"created_at":"2021-03-27 13:30","updated_at":"2021-03-26 05:29","created_by":1,"updated_by":1, "element_details":[{"element_name":"ED","presence":"Yes","length":"25","width":"35"},{"element_name":"Backwall","presence":"Yes","length":"24","width":"34"},{"element_name":"Counter","presence":"Yes","length":"25","width":"35"},{"element_name":"Side 1 Header","presence":"Yes","length":"28","width":"44"},{"element_name":"Side 1 Left Side Pillars","presence":"Yes","length":"96","width":"12"},{"element_name":"Side 1 Right Side Pillars","presence":"Yes","length":"96","width":"12"},{"element_name":"Left Sidewall","presence":"Yes","length":"72","width":"24"},{"element_name":"Right Sidewall","presence":"No","length":"0","width":"0"}]},

{"outlet_id":"823044","visit_id":"VEC873487837934984","outlet_type":"Cigerette Shop","wd_id":"BL5669","market_name":"Diamond Harbour (UA)","merchandiser_name":"Punith","branch":"Bangalore","beat_name":"Wednesday","name":"Samudra Tea Stall","location":"Excellent","contact_no":"9845875948","ra_type":"RA 2","ra_color":"Maroon","store_status":true,"created_at":"2021-03-26 13:30","updated_at":"2021-03-29T05:29:24.341809Z","created_by":1,"updated_by":1,"element_details":[{"element_name":"ED","presence":"Yes","length":"25","width":"35"},{"element_name":"Backwall","presence":"Yes","length":"24","width":"34"},{"element_name":"Counter","presence":"Yes","length":"25","width":"35"},{"element_name":"Side 1 Header","presence":"Yes","length":"28","width":"44"},{"element_name":"Side 1 Left Side Pillars","presence":"Yes","length":"96","width":"12"},{"element_name":"Side 1 Right Side Pillars","presence":"Yes","length":"96","width":"12"},{"element_name":"Left Sidewall","presence":"Yes","length":"72","width":"24"},{"element_name":"Right Sidewall","presence":"Yes","length":"0","width":"0"}]},


{"outlet_id":"456676","visit_id":"VEC873487845435563","outlet_type":"Pan Shop","wd_id":"BL5654","market_name":"DMC (UA)","merchandiser_name":"Virender Singh","location":"Excellent","branch":"Bangalore","beat_name":"Thursday","name":"Vinodh Viklang Pan","contact_no":"9845846575","store_status":true,"ra_type":"RA 1","ra_color":"Golden Yellow","created_at":"2021-03-25 13:30","updated_at":"2021-03-29T05:29:24.341809Z","created_by":1,"updated_by":1,"element_details":[{"element_name":"ED","presence":"Yes","length":"25","width":"35"},{"element_name":"Backwall","presence":"Yes","length":"24","width":"34"},{"element_name":"Counter","presence":"Yes","length":"25","width":"35"},{"element_name":"Side 1 Header","presence":"Yes","length":"28","width":"44"},{"element_name":"Side 1 Left Side Pillars","presence":"Yes","length":"96","width":"12"},{"element_name":"Side 1 Right Side Pillars","presence":"Yes","length":"96","width":"12"},{"element_name":"Left Sidewall","presence":"Yes","length":"72","width":"24"},{"element_name":"Right Sidewall","presence":"Yes","length":"0","width":"0"}]},

{"outlet_id":"456678","visit_id":"VEC984759876456645","outlet_type":"Pan Shop","wd_id":"BL5654","market_name":"DMC (UA)","merchandiser_name":"Hari Singh","location":"Excellent","branch":"Bangalore","beat_name":"Wednesday","name":"Deekishth Pan","contact_no":"9855546575","store_status":true,"ra_type":"RA 2","ra_color":"Amber Yellow","created_at":"2021-03-25 13:30","updated_at":"2021-03-29T05:29:24.341809Z","created_by":1,"updated_by":1,"element_details":[{"element_name":"ED","presence":"Yes","length":"25","width":"35"},{"element_name":"Backwall","presence":"Yes","length":"24","width":"34"},{"element_name":"Counter","presence":"Yes","length":"25","width":"35"},{"element_name":"Side 1 Header","presence":"Yes","length":"28","width":"44"},{"element_name":"Side 1 Left Side Pillars","presence":"Yes","length":"96","width":"12"},{"element_name":"Side 1 Right Side Pillars","presence":"Yes","length":"96","width":"12"},{"element_name":"Left Sidewall","presence":"Yes","length":"72","width":"24"},{"element_name":"Right Sidewall","presence":"Yes","length":"0","width":"0"}]},

{"outlet_id":"466676","visit_id":"VEC873746456796435","outlet_type":"Pan Shop","wd_id":"JA5654","market_name":"DMC (UA)","merchandiser_name":"Hari Singh","location":"Excellent","branch":"JAMMU","beat_name":"Monday","name":"Sunil Pan Shop","contact_no":"9845846435","store_status":true,"ra_type":"RA 2","ra_color":"Amber Yellow","created_at":"2021-03-25 13:30","updated_at":"2021-03-29T05:29:24.341809Z","created_by":1,"updated_by":1,"element_details":[{"element_name":"ED","presence":"Yes","length":"25","width":"35"},{"element_name":"Backwall","presence":"Yes","length":"24","width":"34"},{"element_name":"Counter","presence":"Yes","length":"25","width":"35"},{"element_name":"Side 1 Header","presence":"Yes","length":"28","width":"44"},{"element_name":"Side 1 Left Side Pillars","presence":"Yes","length":"96","width":"12"},{"element_name":"Side 1 Right Side Pillars","presence":"Yes","length":"96","width":"12"},{"element_name":"Left Sidewall","presence":"Yes","length":"72","width":"24"},{"element_name":"Right Sidewall","presence":"Yes","length":"0","width":"0"}]},

{"outlet_id":"236676","visit_id":"VEC873485745968986","outlet_type":"Pan Shop","wd_id":"JA5654","market_name":"DMC (UA)","merchandiser_name":"Hari Singh","location":"Excellent","branch":"JAMMU","beat_name":"Friday","name":"Famous Pan Shop","contact_no":"7845842435","store_status":true,"ra_type":"RA 2","ra_color":"Golden Yellow","created_at":"2021-03-25 13:30","updated_at":"2021-03-29T05:29:24.341809Z","created_by":1,"updated_by":1,"element_details":[{"element_name":"ED","presence":"Yes","length":"25","width":"35"},{"element_name":"Backwall","presence":"Yes","length":"24","width":"34"},{"element_name":"Counter","presence":"Yes","length":"25","width":"35"},{"element_name":"Side 1 Header","presence":"Yes","length":"28","width":"44"},{"element_name":"Side 1 Left Side Pillars","presence":"Yes","length":"96","width":"12"},{"element_name":"Side 1 Right Side Pillars","presence":"Yes","length":"96","width":"12"},{"element_name":"Left Sidewall","presence":"Yes","length":"72","width":"24"},{"element_name":"Right Sidewall","presence":"Yes","length":"0","width":"0"}]}


]};